# Generated by Django 5.1.1 on 2024-09-15 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', message='El nombre debe contener solo letras')], verbose_name='Nombre')),
                ('cuit', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^(\\d{2})-(\\d{8})-(\\d{1})$', message='Debe tener un formato de XX-XXXXXXXX-X')], verbose_name='cuit')),
                ('telefono', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^(\\d{3})-(\\d{7})$', message="El telefono debe contener 10 digitos en un formato de 'XXX-XXXXXXX'")], verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=100, verbose_name='direccion')),
                ('correo', models.EmailField(max_length=254, verbose_name='correo')),
            ],
        ),
    ]
